#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_ch5_artifacts.py

test_result.zip (または展開ディレクトリ) から Chapter 5 用の表(LaTeX)と図(PNG/PDF)を生成する。

想定入力構造（zip/dir共通）:
- test_metrics/theta{IDX}/{dataset}/{dataset}_theta{IDX}_metrics_overall.json
- test_metrics/.../*_exrate_by_status.csv
- test_metrics/.../*_{tag,scenario}_breakdown.csv
- test_log/{dataset}_theta{IDX}_run.jsonl

生成:
- summary/metrics_long.csv, metrics_wide.csv
- tables/*.tex
- figs/*.png|pdf
- (optional) examples/examples_{rq}.md

Author: generated by ChatGPT
"""
from __future__ import annotations

import argparse
import io
import json
import math
import os
import re
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, Iterator, List, Optional, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ----------------------------
# 1) Condition metadata (IDX)
# ----------------------------
# NOTE:
# - ここは「Test最終評価計画ドキュメント」に合わせてラベルを付ける想定。
# - もし将来IDXが増えたら追加。
IDX_INFO: Dict[int, Dict[str, str]] = {
    101: {"rq": "RQ1", "name": r"Baseline-AP", "short": "AP"},
    102: {"rq": "RQ1", "name": r"Baseline-R ($\tau_{\mathrm{conf}}^\ast$)", "short": "R"},
    201: {"rq": "RQ2", "name": r"Proposed ($\theta^\ast$)", "short": "RGGS"},
    301: {"rq": "RQ3", "name": r"Ablate: no OoM-gate", "short": "noOoM"},
    302: {"rq": "RQ3", "name": r"Ablate: no retry", "short": "noRetry"},
    303: {"rq": "RQ3", "name": r"Ablate: no abstain-gate", "short": "noThresh"},
    304: {"rq": "RQ3", "name": r"Ablate: conf-only", "short": "conf_only"},
    305: {"rq": "RQ3", "name": r"Ablate: cos-only", "short": "cos_only"},
    401: {"rq": "RQ4", "name": r"Map variant: $M_{LS}$", "short": "LS"},
    402: {"rq": "RQ4", "name": r"Map variant: $M_{L}$", "short": "L"},
}


DATASET_ORDER = ["test_core", "test_conflict", "test_noisy", "test_oom"]


# ----------------------------
# 2) Data access (zip or dir)
# ----------------------------
@dataclass
class Store:
    path: Path
    zf: Optional[zipfile.ZipFile] = None

    def __post_init__(self):
        if self.path.is_file() and self.path.suffix.lower() == ".zip":
            self.zf = zipfile.ZipFile(self.path, "r")
        else:
            self.zf = None

    def list(self) -> List[str]:
        if self.zf is not None:
            return self.zf.namelist()
        else:
            return [str(p.relative_to(self.path)).replace("\\", "/") for p in self.path.rglob("*") if p.is_file()]

    def open_text(self, rel: str, encoding: str = "utf-8") -> str:
        if self.zf is not None:
            return self.zf.read(rel).decode(encoding)
        else:
            return (self.path / rel).read_text(encoding=encoding)

    def open_bytes(self, rel: str) -> bytes:
        if self.zf is not None:
            return self.zf.read(rel)
        else:
            return (self.path / rel).read_bytes()

    def close(self):
        if self.zf is not None:
            self.zf.close()


# ----------------------------
# 3) Parsing helpers
# ----------------------------
_METRICS_RE = re.compile(r"^test_metrics/theta(?P<theta>\d+)/(?P<ds>[^/]+)/(?P<fname>.+metrics_overall\.json)$")
_EXRATE_RE  = re.compile(r"^test_metrics/theta(?P<theta>\d+)/(?P<ds>[^/]+)/(?P<fname>.+exrate_by_status\.csv)$")
_TAG_RE     = re.compile(r"^test_metrics/theta(?P<theta>\d+)/(?P<ds>[^/]+)/(?P<fname>.+tag_breakdown\.csv)$")
_SCEN_RE    = re.compile(r"^test_metrics/theta(?P<theta>\d+)/(?P<ds>[^/]+)/(?P<fname>.+scenario_breakdown\.csv)$")
_LOG_RE     = re.compile(r"^test_log/(?P<ds>[^/]+)_theta(?P<theta>\d+)_run\.jsonl$")


def _safe_div(a: float, b: float) -> float:
    return float(a) / float(b) if b not in (0, 0.0) else float("nan")


def parse_metrics(store: Store) -> pd.DataFrame:
    rows = []
    for rel in store.list():
        m = _METRICS_RE.match(rel)
        if not m:
            continue
        theta = int(m.group("theta"))
        ds = m.group("ds")
        d = json.loads(store.open_text(rel))
        op = d.get("operating_point", {})

        # counts
        in_n_ok = op.get("in_n_ok", 0)
        oom_n_ok = op.get("oom_n_ok", 0)
        in_n_correct_accept = op.get("in_n_correct_accept", 0)
        in_n_accepted = op.get("in_n_accepted", 0)
        in_n_wrong_accept = op.get("in_n_wrong_accept", 0)

        # metrics derived (match thesis definitions)
        acc_in = _safe_div(in_n_correct_accept, in_n_ok)
        coverage = float(op.get("in_coverage", float("nan")))
        selrisk = float(op.get("in_selective_risk", float("nan")))
        abstain = float("nan")
        if not math.isnan(coverage):
            abstain = 1.0 - coverage

        oom_fa = float(op.get("oom_false_accept_rate", float("nan")))
        acc_oom = float(op.get("oom_true_reject_rate", float("nan")))  # correct is reject in OoM set

        ex = d.get("exrate", {}) if isinstance(d.get("exrate", {}), dict) else {}
        ex_total = float(ex.get("exrate_total", float("nan")))
        ex_in = float(ex.get("exrate_in", float("nan")))
        ex_oom = float(ex.get("exrate_oom", float("nan")))

        rows.append({
            "theta": theta,
            "rq": IDX_INFO.get(theta, {}).get("rq", ""),
            "method": IDX_INFO.get(theta, {}).get("name", f"theta{theta}"),
            "method_short": IDX_INFO.get(theta, {}).get("short", f"{theta}"),
            "dataset": ds,
            "acc_in": acc_in,
            "coverage": coverage,
            "abstain": abstain,
            "selrisk": selrisk,
            "oom_fa": oom_fa,
            "acc_oom": acc_oom,
            "exrate_total": ex_total,
            "exrate_in": ex_in,
            "exrate_oom": ex_oom,
            "in_n_ok": in_n_ok,
            "in_n_accepted": in_n_accepted,
            "in_n_wrong_accept": in_n_wrong_accept,
            "oom_n_ok": oom_n_ok,
        })

    df = pd.DataFrame(rows)
    if df.empty:
        raise RuntimeError("metrics_overall.json が見つかりません。入力パスが test_result.zip / 展開ディレクトリか確認してください。")
    # order
    df["dataset"] = pd.Categorical(df["dataset"], categories=DATASET_ORDER, ordered=True)
    df = df.sort_values(["theta", "dataset"]).reset_index(drop=True)
    return df


def parse_breakdown_csv(store: Store, regex: re.Pattern) -> pd.DataFrame:
    rows = []
    for rel in store.list():
        m = regex.match(rel)
        if not m:
            continue
        theta = int(m.group("theta"))
        ds = m.group("ds")
        b = store.open_bytes(rel)
        df = pd.read_csv(io.BytesIO(b))
        df["theta"] = theta
        df["dataset"] = ds
        rows.append(df)
    if not rows:
        return pd.DataFrame()
    out = pd.concat(rows, ignore_index=True)
    out["dataset"] = pd.Categorical(out["dataset"], categories=DATASET_ORDER, ordered=True)
    return out


def parse_logs(store: Store) -> Dict[Tuple[int, str], pd.DataFrame]:
    out: Dict[Tuple[int, str], pd.DataFrame] = {}
    for rel in store.list():
        m = _LOG_RE.match(rel)
        if not m:
            continue
        ds = m.group("ds")
        theta = int(m.group("theta"))
        # read jsonl
        text = store.open_text(rel)
        rows = [json.loads(line) for line in text.splitlines() if line.strip()]
        df = pd.DataFrame(rows)
        out[(theta, ds)] = df
    return out


# ----------------------------
# 4) Output helpers
# ----------------------------
def ensure_dir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)


def df_to_latex_table(df: pd.DataFrame, caption: str, label: str, out_path: Path, *, float_fmt: str = "%.3f"):
    """
    booktabs形式で LaTeX 表を書き出す（最小限のラッパ）
    """
    latex = df.to_latex(index=False, escape=False, float_format=lambda x: float_fmt % x, longtable=False)
    s = []
    s.append(r"\begin{table}[t]")
    s.append(r"\centering")
    s.append(latex)
    s.append(rf"\caption{{{caption}}}")
    s.append(rf"\label{{{label}}}")
    s.append(r"\end{table}")
    out_path.write_text("\n".join(s) + "\n", encoding="utf-8")


def save_fig(fig, out_path: Path):
    fig.tight_layout()
    fig.savefig(out_path, dpi=200)
    plt.close(fig)


# ----------------------------
# 5) Table builders (RQ-wise)
# ----------------------------
def build_rq_tables(metrics: pd.DataFrame, out_dir: Path) -> None:
    ensure_dir(out_dir)

    # common columns per dataset type
    cols_in = ["acc_in", "abstain", "selrisk", "exrate_total"]
    cols_oom = ["oom_fa", "acc_oom", "exrate_total"]

    def _format_block(df_sub: pd.DataFrame, cols: List[str]) -> pd.DataFrame:
        x = df_sub[["theta", "method", "dataset"] + cols].copy()
        return x

    # RQ1: 101,102
    rq1 = metrics[metrics["theta"].isin([101, 102])].copy()
    df_to_latex_table(
        _format_block(rq1, cols_in + cols_oom),
        caption="RQ1: LLM-only Baselines の Test 最終評価（主要指標）",
        label="tab:rq1_test_overall",
        out_path=out_dir / "rq1_test_overall.tex",
    )

    # RQ2: 201 vs 101/102
    rq2 = metrics[metrics["theta"].isin([101, 102, 201])].copy()
    df_to_latex_table(
        _format_block(rq2, cols_in + cols_oom),
        caption="RQ2: 提案法 $\\theta^*$ と Baselines の Test 最終評価（主要指標）",
        label="tab:rq2_test_overall",
        out_path=out_dir / "rq2_test_overall.tex",
    )

    # RQ3: 201 vs 301..305 (delta)
    base = metrics[metrics["theta"] == 201].set_index(["dataset"])
    abls = metrics[metrics["theta"].isin([301, 302, 303, 304, 305])].copy()
    rows = []
    for _, r in abls.iterrows():
        ds = r["dataset"]
        b = base.loc[ds]
        for m in ["acc_in", "abstain", "selrisk", "oom_fa", "acc_oom", "exrate_total"]:
            rows.append({
                "theta": int(r["theta"]),
                "method": r["method"],
                "dataset": ds,
                "metric": m,
                "delta": float(r[m]) - float(b[m]) if (not pd.isna(r[m]) and not pd.isna(b[m])) else np.nan,
                "value": float(r[m]),
                "base": float(b[m]),
            })
    ddf = pd.DataFrame(rows)
    # wide delta (metric columns)
    wide = ddf.pivot_table(index=["theta", "method", "dataset"], columns="metric", values="delta").reset_index()
    df_to_latex_table(
        wide,
        caption="RQ3: アブレーションの効果（基準=提案法 $\\theta^*$，差分=各条件−基準）",
        label="tab:rq3_ablation_delta",
        out_path=out_dir / "rq3_ablation_delta.tex",
    )

    # RQ4: map variants 401,402,201
    rq4 = metrics[metrics["theta"].isin([402, 401, 201])].copy()
    df_to_latex_table(
        _format_block(rq4, cols_in + cols_oom),
        caption="RQ4: 地図側意味情報の設計差（$M_{LSD}$ vs $M_{LS}$ vs $M_L$）による Test 最終評価（主要指標）",
        label="tab:rq4_map_variants",
        out_path=out_dir / "rq4_map_variants.tex",
    )

    # Also export a "pretty" wide table: rows=method, cols=(dataset, metric)
    pretty = metrics.copy()
    pretty["row"] = pretty["method_short"]
    pretty = pretty.set_index(["row", "dataset"])[["acc_in", "abstain", "selrisk", "oom_fa", "acc_oom", "exrate_total"]]
    pretty_wide = pretty.unstack("dataset")
    pretty_wide.columns = [f"{c1}_{c2}" for (c1, c2) in pretty_wide.columns]
    pretty_wide = pretty_wide.reset_index()
    pretty_wide.to_csv(out_dir / "all_methods_wide.csv", index=False)


# ----------------------------
# 6) Figure builders
# ----------------------------
# ---- risk_coverage の点ラベル(Prop/cos/noRetry等)が重なるのを避けるためのオフセット(単位: points) ----
# ※追加ライブラリを入れずに、matplotlib標準機能だけで制御するための最小実装。
_RISK_LABEL_OFFSET_PRESET = {
    # 相談で「特に重なる」と言及があったものは固定で散らす
    "RGGS": (4, -4),      # 左上
    "noRetry": (-4, -4), # 左下
    "cos_only": (4, 4),       # 右下
}

# preset以外のラベルは順番にこの候補を回して配置する（右上/右下/左下/左上…を繰り返す）
_RISK_LABEL_OFFSET_CYCLE = [
    (4, 4), (4, -4), (-4, -4), (-4, 4),
    (4, 4), (4, -4), (-4, -4), (-4, 4),
]

def plot_risk_coverage(metrics: pd.DataFrame, out_dir: Path, fmt: str) -> None:
    ensure_dir(out_dir)
    in_datasets = ["test_core", "test_conflict", "test_noisy"]
    for ds in in_datasets:
        sub = metrics[metrics["dataset"] == ds].copy()
        sub = sub.dropna(subset=["coverage", "selrisk"])
        if sub.empty:
            continue

        # θ順に揃えて、ラベル配置の再現性を確保
        if "theta" in sub.columns:
            sub = sub.sort_values("theta")

        fig = plt.figure(figsize=(6.5, 4.0))
        ax = fig.add_subplot(111)
        ax.scatter(sub["coverage"], sub["selrisk"])

        # 点ラベルが重ならないように、ラベルごとにオフセットを変える
        cycle_i = 0
        for _, r in sub.iterrows():
            label = str(r["method_short"])
            x = float(r["coverage"])
            y = float(r["selrisk"])

            if label in _RISK_LABEL_OFFSET_PRESET:
                dx, dy = _RISK_LABEL_OFFSET_PRESET[label]
            else:
                dx, dy = _RISK_LABEL_OFFSET_CYCLE[cycle_i % len(_RISK_LABEL_OFFSET_CYCLE)]
                cycle_i += 1

            ha = "left" if dx >= 0 else "right"
            va = "bottom" if dy >= 0 else "top"

            ax.annotate(
                label,
                (x, y),
                textcoords="offset points",
                xytext=(dx, dy),
                ha=ha,
                va=va,
                fontsize=9,
            )

        ax.set_xlabel("Coverage")
        # ax.set_xlabel("Coverage (in-map accept rate)")
        ax.set_ylabel("SelRisk")
        # ax.set_ylabel("SelRisk (wrong-accept | accept)")

        # 端の点でラベルが図の外に出て切れやすいので、少しだけ余白を追加
        ax.margins(x=0.06, y=0.10)

        ax.grid(True, alpha=0.3)
        save_fig(fig, out_dir / f"risk_coverage_{ds}.{fmt}")



def plot_oom_fa(metrics: pd.DataFrame, out_dir: Path, fmt: str) -> None:
    ensure_dir(out_dir)
    sub = metrics[metrics["dataset"] == "test_oom"].copy()
    sub = sub.dropna(subset=["oom_fa"])
    if sub.empty:
        return
    sub = sub.sort_values("theta")
    n = len(sub)

    # 横軸ラベルが重ならないように: 図を横長に（bar数に応じて自動調整）+ 斜め表示
    fig_w = max(7.5, 0.65 * n + 2.0)
    fig = plt.figure(figsize=(fig_w, 3.8))
    ax = fig.add_subplot(111)

    ax.bar(sub["method_short"], sub["oom_fa"])
    ax.set_xlabel("Condition")
    ax.set_ylabel("OoM_FA")
    # ax.set_ylabel("OoM_FA (false accept rate)")
    ax.set_ylim(0, 1.0)
    ax.grid(True, axis="y", alpha=0.3)

    # tick labelの重なり対策（必要十分な範囲で）
    ax.tick_params(axis="x", labelrotation=0)
    for t in ax.get_xticklabels():
        t.set_ha("center")

    save_fig(fig, out_dir / f"oom_false_accept.{fmt}")


def plot_exrate(metrics: pd.DataFrame, out_dir: Path, fmt: str) -> None:
    ensure_dir(out_dir)
    for ds in DATASET_ORDER:
        sub = metrics[metrics["dataset"] == ds].copy()
        sub = sub.dropna(subset=["exrate_total"])
        if sub.empty:
            continue

        sub = sub.sort_values("theta")
        n = len(sub)

        # 横軸ラベルが重ならないように: 図を横長に（bar数に応じて自動調整）+ 斜め表示
        fig_w = max(7.5, 0.65 * n + 2.0)
        fig = plt.figure(figsize=(fig_w, 3.8))
        ax = fig.add_subplot(111)

        ax.bar(sub["method_short"], sub["exrate_total"])
        ax.set_xlabel("Condition")
        ax.set_ylabel(r"ExRate$_{total}$")

        ax.set_ylim(0, max(0.1, float(sub["exrate_total"].max()) * 1.2))
        ax.grid(True, axis="y", alpha=0.3)

        ax.tick_params(axis="x", labelrotation=0)
        for t in ax.get_xticklabels():
            t.set_ha("center")

        save_fig(fig, out_dir / f"exrate_total_{ds}.{fmt}")



def plot_ablation_heatmap(metrics: pd.DataFrame, out_dir: Path, fmt: str) -> None:
    """
    RQ3向け: 各datasetで (ablation x metric) のΔヒートマップを描く（基準=θ=201）
    """
    ensure_dir(out_dir)
    base = metrics[metrics["theta"] == 201].set_index(["dataset"])
    abls = metrics[metrics["theta"].isin([301, 302, 303, 304, 305])].copy()

    metrics_list = ["acc_in", "abstain", "selrisk", "oom_fa", "acc_oom", "exrate_total"]
    abls_order = [301, 302, 303, 304, 305]

    for ds in DATASET_ORDER:
        mat = []
        labels = []
        for t in abls_order:
            row = abls[(abls["theta"] == t) & (abls["dataset"] == ds)]
            if row.empty:
                continue
            r = row.iloc[0]
            b = base.loc[ds]
            v = []
            for m in metrics_list:
                if pd.isna(r[m]) or pd.isna(b[m]):
                    v.append(np.nan)
                else:
                    v.append(float(r[m]) - float(b[m]))
            mat.append(v)
            labels.append(IDX_INFO.get(t, {}).get("short", str(t)))
        if not mat:
            continue
        A = np.array(mat, dtype=float)
        fig = plt.figure(figsize=(10, 4))
        ax = fig.add_subplot(111)
        im = ax.imshow(A, aspect="auto")
        ax.set_yticks(range(len(labels)))
        ax.set_yticklabels(labels)
        ax.set_xticks(range(len(metrics_list)))
        ax.set_xticklabels(metrics_list, rotation=30, ha="right")
        ax.set_title(f"Δ (ablation - base) for {ds} (base=theta201)")
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
        save_fig(fig, out_dir / f"ablation_delta_heatmap_{ds}.{fmt}")


# ----------------------------
# 7) Example extraction (minimal)
# ----------------------------
def extract_examples(logs: Dict[Tuple[int, str], pd.DataFrame], out_dir: Path) -> None:
    """
    各RQにつき、(成功例 / 危険誤受理例 / 有益な棄権例) を1～2件ずつ抽出する（最小限）。
    - ここでは自動抽出のため、厳密な「代表性」は保証しない。
    - 章に載せる際は、人手で最終選定することを推奨。
    """
    ensure_dir(out_dir)

    def pick_one(df: pd.DataFrame, cond) -> Optional[pd.Series]:
        x = df[cond].copy()
        if x.empty:
            return None
        # deterministic: sort by query text if available
        if "q" in x.columns:
            x = x.sort_values("q")
        return x.iloc[0]

    # Use theta201 on core by default
    for ds in ["test_core", "test_conflict", "test_noisy"]:
        key = (201, ds)
        if key not in logs:
            continue
        df = logs[key]
        df_ok = df[df["status"] == "ok"].copy()

        suc = pick_one(df_ok, (df_ok["accept"] == True) & (df_ok["y"] != -1) & (df_ok["y_hat"] == df_ok["y"]))
        dang = pick_one(df_ok, (df_ok["accept"] == True) & (df_ok["y"] != -1) & (df_ok["y_hat"] != df_ok["y"]))
        abst = pick_one(df_ok, (df_ok["accept"] == False) & (df_ok["y"] != -1))

        lines = []
        lines.append(f"# Examples from theta201 ({ds})")
        for title, ex in [("成功例", suc), ("危険誤受理例（WA）", dang), ("有益な棄権例", abst)]:
            lines.append(f"## {title}")
            if ex is None:
                lines.append("(該当なし)")
                continue
            # show minimal fields
            for k in ["id", "q", "y", "y_hat", "accept", "status", "conf", "cos", "combined", "tags", "scenario"]:
                if k in ex.index:
                    lines.append(f"- {k}: {ex[k]}")
        (out_dir / f"examples_theta201_{ds}.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


# ----------------------------
# 8) Main
# ----------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, help="test_result.zip または展開ディレクトリへのパス")
    ap.add_argument("--out", required=True, help="出力ディレクトリ")
    ap.add_argument("--fig_format", default="png", choices=["png", "pdf"], help="図の拡張子")
    ap.add_argument("--include_heatmap", action="store_true", help="RQ3向けΔヒートマップも生成")
    ap.add_argument("--include_examples", action="store_true", help="代表例抽出（最小限）も生成")
    args = ap.parse_args()

    store = Store(Path(args.input))
    out = Path(args.out)
    ensure_dir(out)

    # 1) metrics
    metrics = parse_metrics(store)
    ensure_dir(out / "summary")
    metrics.to_csv(out / "summary" / "metrics_long.csv", index=False)

    # also wide
    wide = metrics.pivot_table(index=["theta", "method", "method_short"], columns="dataset",
                               values=["acc_in", "abstain", "selrisk", "oom_fa", "acc_oom", "exrate_total"])
    wide.columns = [f"{m}_{ds}" for (m, ds) in wide.columns]
    wide = wide.reset_index()
    wide.to_csv(out / "summary" / "metrics_wide.csv", index=False)

    # 2) tables
    build_rq_tables(metrics, out / "tables")

    # 3) figures
    plot_risk_coverage(metrics, out / "figs", args.fig_format)
    plot_oom_fa(metrics, out / "figs", args.fig_format)
    plot_exrate(metrics, out / "figs", args.fig_format)
    if args.include_heatmap:
        plot_ablation_heatmap(metrics, out / "figs", args.fig_format)

    # 4) breakdown CSVs (optional export)
    ex_df = parse_breakdown_csv(store, _EXRATE_RE)
    if not ex_df.empty:
        ex_df.to_csv(out / "summary" / "exrate_by_status_long.csv", index=False)
    tag_df = parse_breakdown_csv(store, _TAG_RE)
    if not tag_df.empty:
        tag_df.to_csv(out / "summary" / "tag_breakdown_long.csv", index=False)
    scen_df = parse_breakdown_csv(store, _SCEN_RE)
    if not scen_df.empty:
        scen_df.to_csv(out / "summary" / "scenario_breakdown_long.csv", index=False)

    # 5) examples (minimal)
    if args.include_examples:
        logs = parse_logs(store)
        extract_examples(logs, out / "examples")

    store.close()
    print(f"[OK] outputs written to: {out.resolve()}")


if __name__ == "__main__":
    main()
